// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY4VqBTxxFK237rvHopoALFQa9MhECDhg',
    appId: '1:263455625090:web:4b6584b1fcece1978e099b',
    messagingSenderId: '263455625090',
    projectId: 'snusvault-fca18',
    authDomain: 'snusvault-fca18.firebaseapp.com',
    storageBucket: 'snusvault-fca18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD35QFEhCiCyieMToZgGXH3GJ4PXGRilkw',
    appId: '1:263455625090:android:f860a9fdc637c1648e099b',
    messagingSenderId: '263455625090',
    projectId: 'snusvault-fca18',
    storageBucket: 'snusvault-fca18.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY4VqBTxxFK237rvHopoALFQa9MhECDhg',
    appId: '1:263455625090:web:48b3eae2a6894f388e099b',
    messagingSenderId: '263455625090',
    projectId: 'snusvault-fca18',
    authDomain: 'snusvault-fca18.firebaseapp.com',
    storageBucket: 'snusvault-fca18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX7cnucdRMuz4Cu1tac_QN1l5WUTMwj1I',
    appId: '1:263455625090:ios:37103134fd1177b08e099b',
    messagingSenderId: '263455625090',
    projectId: 'snusvault-fca18',
    storageBucket: 'snusvault-fca18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX7cnucdRMuz4Cu1tac_QN1l5WUTMwj1I',
    appId: '1:263455625090:ios:37103134fd1177b08e099b',
    messagingSenderId: '263455625090',
    projectId: 'snusvault-fca18',
    storageBucket: 'snusvault-fca18.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}